baseURL = 'srenninger.github.io'
languageCode = 'en-us'
title = 'Dr. Sabine L. Renninger'
pluralizelisttitles = false
[markup.goldmark.renderer]
unsafe = true # Allow HTML in md files
[markup.goldmark.parser.attribute]
block = true
title = true